/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject2;

public class App {
   
    public static void main(String[] args) {
        Veiculo fusca = new Veiculo(new Motor_Fusca());
        Veiculo lamborgini = new Veiculo(new Motor_Lamborgini());
        Veiculo ferrari = new Veiculo(new Motor_Ferrari());
        Veiculo BMW = new Veiculo(new Motor_BMW());
        
        System.out.println(fusca.acelerar());
        System.out.println(ferrari.acelerar());
        System.out.println(lamborgini.acelerar());
        System.out.println(BMW.acelerar());
    }
}
